import type { MockApp, MockRelease } from '@/types/app'

export const MOCK_APPS: MockApp[] = [
  // Finance org
  {
    id: 'app-finance-ios',
    name: 'FinanceTracker',
    platform: 'IOS',
    iconUrl: null,
    org: { name: 'Finance', slug: 'finance' },
    latestRelease: {
      version: '2.1.0',
      releaseType: 'BETA',
      createdAt: '2026-01-28T10:00:00Z',
    },
    testerCount: 24,
    totalDownloads: 312,
  },
  {
    id: 'app-finance-android',
    name: 'FinanceTracker',
    platform: 'ANDROID',
    iconUrl: null,
    org: { name: 'Finance', slug: 'finance' },
    latestRelease: {
      version: '2.0.3',
      releaseType: 'RELEASE_CANDIDATE',
      createdAt: '2026-01-25T14:00:00Z',
    },
    testerCount: 18,
    totalDownloads: 198,
  },
  // Sales org
  {
    id: 'app-sales-crm',
    name: 'SalesPulse CRM',
    platform: 'IOS',
    iconUrl: null,
    org: { name: 'Sales', slug: 'sales' },
    latestRelease: {
      version: '1.4.0',
      releaseType: 'ALPHA',
      createdAt: '2026-02-01T09:00:00Z',
    },
    testerCount: 12,
    totalDownloads: 87,
  },
  {
    id: 'app-sales-reports',
    name: 'Sales Reports',
    platform: 'IOS',
    iconUrl: null,
    org: { name: 'Sales', slug: 'sales' },
    latestRelease: {
      version: '3.0.0',
      releaseType: 'BETA',
      createdAt: '2026-01-30T11:00:00Z',
    },
    testerCount: 35,
    totalDownloads: 540,
  },
  // Marketing org
  {
    id: 'app-marketing-android',
    name: 'CampaignHub',
    platform: 'ANDROID',
    iconUrl: null,
    org: { name: 'Marketing', slug: 'marketing' },
    latestRelease: {
      version: '1.0.1',
      releaseType: 'BETA',
      createdAt: '2026-02-03T16:00:00Z',
    },
    testerCount: 8,
    totalDownloads: 52,
  },
  {
    id: 'app-marketing-ios',
    name: 'BrandKit',
    platform: 'IOS',
    iconUrl: null,
    org: { name: 'Marketing', slug: 'marketing' },
    latestRelease: {
      version: '0.9.0',
      releaseType: 'ALPHA',
      createdAt: '2026-02-05T08:00:00Z',
    },
    testerCount: 10,
    totalDownloads: 34,
  },
]

export const MOCK_RELEASES: MockRelease[] = [
  // FinanceTracker iOS
  {
    id: 'rel-ft-ios-1',
    appId: 'app-finance-ios',
    version: '2.1.0',
    buildNumber: '42',
    releaseType: 'BETA',
    releaseNotes:
      'Improved dashboard performance. Fixed a crash when opening the portfolio view on iOS 17. Added dark mode support for charts.',
    fileSize: 18_432_000,
    downloadCount: 312,
    createdAt: '2026-01-28T10:00:00Z',
  },
  {
    id: 'rel-ft-ios-2',
    appId: 'app-finance-ios',
    version: '2.0.0',
    buildNumber: '38',
    releaseType: 'RELEASE_CANDIDATE',
    releaseNotes:
      'Major redesign of the main navigation. New budget planner feature. Performance improvements across all screens.',
    fileSize: 17_920_000,
    downloadCount: 0,
    createdAt: '2026-01-10T14:00:00Z',
  },
  {
    id: 'rel-ft-ios-3',
    appId: 'app-finance-ios',
    version: '1.9.5',
    buildNumber: '35',
    releaseType: 'ALPHA',
    releaseNotes: 'Internal testing build. Experimental chart components.',
    fileSize: 16_384_000,
    downloadCount: 0,
    createdAt: '2025-12-20T09:00:00Z',
  },
  // FinanceTracker Android
  {
    id: 'rel-ft-android-1',
    appId: 'app-finance-android',
    version: '2.0.3',
    buildNumber: '29',
    releaseType: 'RELEASE_CANDIDATE',
    releaseNotes:
      'Release candidate for v2.0. Fixed widget refresh bug. Optimized background sync.',
    fileSize: 22_528_000,
    downloadCount: 198,
    createdAt: '2026-01-25T14:00:00Z',
  },
  {
    id: 'rel-ft-android-2',
    appId: 'app-finance-android',
    version: '2.0.0',
    buildNumber: '25',
    releaseType: 'BETA',
    releaseNotes:
      'Android v2 beta. Ported all new features from iOS. Material You support added.',
    fileSize: 21_504_000,
    downloadCount: 0,
    createdAt: '2026-01-05T12:00:00Z',
  },
  // SalesPulse CRM
  {
    id: 'rel-crm-1',
    appId: 'app-sales-crm',
    version: '1.4.0',
    buildNumber: '17',
    releaseType: 'ALPHA',
    releaseNotes:
      'Early access to the new pipeline view. Lead scoring algorithm updated.',
    fileSize: 14_336_000,
    downloadCount: 87,
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'rel-crm-2',
    appId: 'app-sales-crm',
    version: '1.3.2',
    buildNumber: '15',
    releaseType: 'BETA',
    releaseNotes:
      'Bug fixes for contact sync. Improved push notification delivery.',
    fileSize: 13_824_000,
    downloadCount: 0,
    createdAt: '2026-01-15T11:00:00Z',
  },
  // Sales Reports
  {
    id: 'rel-sr-1',
    appId: 'app-sales-reports',
    version: '3.0.0',
    buildNumber: '55',
    releaseType: 'BETA',
    releaseNotes:
      'Complete rewrite with SwiftUI. PDF export now supports all chart types. Real-time data sync.',
    fileSize: 19_456_000,
    downloadCount: 540,
    createdAt: '2026-01-30T11:00:00Z',
  },
  {
    id: 'rel-sr-2',
    appId: 'app-sales-reports',
    version: '2.8.1',
    buildNumber: '52',
    releaseType: 'RELEASE_CANDIDATE',
    releaseNotes: 'Final RC for 2.x series. Minor stability fixes.',
    fileSize: 18_944_000,
    downloadCount: 0,
    createdAt: '2026-01-18T15:00:00Z',
  },
  {
    id: 'rel-sr-3',
    appId: 'app-sales-reports',
    version: '2.8.0',
    buildNumber: '50',
    releaseType: 'BETA',
    releaseNotes: 'New quarterly comparison charts. CSV export feature.',
    fileSize: 18_432_000,
    downloadCount: 0,
    createdAt: '2026-01-08T10:00:00Z',
  },
  // CampaignHub
  {
    id: 'rel-ch-1',
    appId: 'app-marketing-android',
    version: '1.0.1',
    buildNumber: '8',
    releaseType: 'BETA',
    releaseNotes: 'Fixed campaign creation crash. Improved image upload speed.',
    fileSize: 12_288_000,
    downloadCount: 52,
    createdAt: '2026-02-03T16:00:00Z',
  },
  {
    id: 'rel-ch-2',
    appId: 'app-marketing-android',
    version: '1.0.0',
    buildNumber: '5',
    releaseType: 'ALPHA',
    releaseNotes: 'Initial alpha release. Core campaign management features.',
    fileSize: 11_776_000,
    downloadCount: 0,
    createdAt: '2026-01-22T13:00:00Z',
  },
  // BrandKit
  {
    id: 'rel-bk-1',
    appId: 'app-marketing-ios',
    version: '0.9.0',
    buildNumber: '12',
    releaseType: 'ALPHA',
    releaseNotes:
      'Pre-release build. Asset library browsing. Brand guideline viewer.',
    fileSize: 15_360_000,
    downloadCount: 34,
    createdAt: '2026-02-05T08:00:00Z',
  },
  {
    id: 'rel-bk-2',
    appId: 'app-marketing-ios',
    version: '0.8.5',
    buildNumber: '10',
    releaseType: 'ALPHA',
    releaseNotes: 'Early prototype. Logo management and color palette features.',
    fileSize: 14_848_000,
    downloadCount: 0,
    createdAt: '2026-01-27T09:00:00Z',
  },
]
